// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAURbuwLpzE1eAaVSXelWWyFLycx_0fDrA',
    appId: '1:509885888144:web:18f36b0dcacc6fb7cc0a15',
    messagingSenderId: '509885888144',
    projectId: 'zegoapp-fc248',
    authDomain: 'zegoapp-fc248.firebaseapp.com',
    storageBucket: 'zegoapp-fc248.firebasestorage.app',
    measurementId: 'G-EMQJX2MCLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyx79d0bKrm5bB6DWaynocdOHIIyAt0wk',
    appId: '1:509885888144:android:d1531b428eb43f75cc0a15',
    messagingSenderId: '509885888144',
    projectId: 'zegoapp-fc248',
    storageBucket: 'zegoapp-fc248.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7pNGnzT81k-358hGbduOfzAJCRhGwKi0',
    appId: '1:509885888144:ios:8e1ac36afd100dbacc0a15',
    messagingSenderId: '509885888144',
    projectId: 'zegoapp-fc248',
    storageBucket: 'zegoapp-fc248.firebasestorage.app',
    iosBundleId: 'com.example.callingZegocloud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7pNGnzT81k-358hGbduOfzAJCRhGwKi0',
    appId: '1:509885888144:ios:8e1ac36afd100dbacc0a15',
    messagingSenderId: '509885888144',
    projectId: 'zegoapp-fc248',
    storageBucket: 'zegoapp-fc248.firebasestorage.app',
    iosBundleId: 'com.example.callingZegocloud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAURbuwLpzE1eAaVSXelWWyFLycx_0fDrA',
    appId: '1:509885888144:web:a7174d20aef05167cc0a15',
    messagingSenderId: '509885888144',
    projectId: 'zegoapp-fc248',
    authDomain: 'zegoapp-fc248.firebaseapp.com',
    storageBucket: 'zegoapp-fc248.firebasestorage.app',
    measurementId: 'G-YQSMHQBTSR',
  );
}
